# Generated by Django 2.0.3 on 2018-04-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0004_auto_20180403_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='last_name',
            field=models.IntegerField(),
        ),
    ]
