# Generated by Django 2.2.6 on 2019-10-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0006_auto_20180403_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightningTalk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('items_to_bring', models.TextField(blank=True, help_text='This should only be on Lightning Talks')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.Event')),
                ('speakers', models.ManyToManyField(blank=True, to='simple_app.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('upload', models.FileField(blank=True, help_text='This is unique to Featured Sessions', upload_to='uploads/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.Event')),
                ('speakers', models.ManyToManyField(blank=True, to='simple_app.Speaker')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
